version: '3'

services:

  activemq:
    image: vromero/activemq-artemis
    container_name: kind_feistel
    environment:
      - "TZ=Europe/Amsterdam"
    volumes:
      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61613:61613"
      - "8161:8161"
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testdocker
      - POSTGRES_PASSWORD=testdocker
      - POSTGRES_DB=testdocker
